FROM python:3.6
RUN pip install -U \
  aio-pika==6.6.0 \
  aiormq==3.2.1 \
  appdirs==1.4.3 \
  bcrypt==3.1.7 \
  cached-property==1.5.1 \
  cffi==1.14.0 \
  cryptography==2.9 \
  distlib==0.3.0 \
  docker==4.2.0 \
  docker-compose==1.25.5 \
  dockerpty==0.4.1 \
  docopt==0.6.2 \
  filelock==3.0.12 \
  idna==2.9 \
  importlib-metadata==1.6.0 \
  importlib-resources==1.4.0 \
  multidict==4.7.5 \
  mysql-connector==2.2.9 \
  pamqp==2.3.0 \
  paramiko==2.7.1 \
  pbr==5.4.5 \
  pycparser==2.20 \
  PyNaCl==1.3.0 \
  requests==2.23.0 \
  stevedore==1.32.0 \
  texttable==1.6.2 \
  virtualenv==20.0.18 \
  virtualenv-clone==0.5.4 \
  virtualenvwrapper==4.8.4 \
  websocket-client==0.57.0 \
  yarl==1.4.2 \
  zipp==3.1.0
ADD ./dreams-master /dreams-master
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["python3", "/dreams-master/mq-dreams/consumer-dreams.py"]
